/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PrescriptionPartialV4 } from "./PrescriptionPartialV4";
import { PrescriptionStatusV4 } from "./PrescriptionStatusV4";

export class PrescriptionListV4 {
  constructor(json: JSON | any) {
    Object.assign(this as PrescriptionListV4, json)
  }

  id?: string
  partial?: PrescriptionPartialV4
  status?: PrescriptionStatusV4
}
