/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PrescriptionV4 } from "./PrescriptionV4";

export class PrescriptionPartialV4 {
  constructor(json: JSON | any) {
    Object.assign(this as PrescriptionPartialV4, json)
  }

  hasHidden?: boolean
  hasMoreResults?: boolean
  prescriptions?: PrescriptionV4[]
}
